window.CKO_TRICKS = [
  { id: "level-1-1", level: 1, code: "LEVEL 1-1", zhName: "章鱼烧", score: 1 },
  { id: "level-1-2", level: 1, code: "LEVEL 1-2", zhName: "止剑", score: 1 },
  { id: "level-1-3", level: 1, code: "LEVEL 1-3", zhName: "中皿", score: 1 },
  { id: "level-1-4", level: 1, code: "LEVEL 1-4", zhName: "飞行机", score: 1 },
  { id: "level-1-5", level: 1, code: "LEVEL 1-5", zhName: "烛台", score: 1 },
  { id: "level-1-6", level: 1, code: "LEVEL 1-6", zhName: "大皿，轨道一周", score: 1 },
  { id: "level-1-7", level: 1, code: "LEVEL 1-7", zhName: "抽线拍手", score: 1 },
  { id: "level-1-8", level: 1, code: "LEVEL 1-8", zhName: "大皿，止剑", score: 1 },
  { id: "level-1-9", level: 1, code: "LEVEL 1-9", zhName: "日本一周", score: 1 },
  { id: "level-1-10", level: 1, code: "LEVEL 1-10", zhName: "皿上来回x10或更多", score: 1 },

  { id: "level-2-1", level: 2, code: "LEVEL 2-1", zhName: "飞行机，敬酒跳剑", score: 2 },
  { id: "level-2-2", level: 2, code: "LEVEL 2-2", zhName: "棒球", score: 2 },
  { id: "level-2-3", level: 2, code: "LEVEL 2-3", zhName: "世界一周", score: 2 },
  { id: "level-2-4", level: 2, code: "LEVEL 2-4", zhName: "剑顶滑玉", score: 2 },
  { id: "level-2-5", level: 2, code: "LEVEL 2-5", zhName: "飞镖", score: 2 },
  { id: "level-2-6", level: 2, code: "LEVEL 2-6", zhName: "游泳，竹蜻蜓", score: 2 },
  { id: "level-2-7", level: 2, code: "LEVEL 2-7", zhName: "空中飞人", score: 2 },
  { id: "level-2-8", level: 2, code: "LEVEL 2-8", zhName: "1回转灯台，持球收", score: 2 },
  { id: "level-2-9", level: 2, code: "LEVEL 2-9", zhName: "天中杀", score: 2 },
  { id: "level-2-10", level: 2, code: "LEVEL 2-10", zhName: "瓢虫，止剑", score: 2 },

  { id: "level-3-1", level: 3, code: "LEVEL 3-1", zhName: "中皿，幽灵持球收", score: 3 },
  { id: "level-3-2", level: 3, code: "LEVEL 3-2", zhName: "天地二段", score: 3 },
  { id: "level-3-3", level: 3, code: "LEVEL 3-3", zhName: "游泳，离转地球", score: 3 },
  { id: "level-3-4", level: 3, code: "LEVEL 3-4", zhName: "月面，持球收", score: 3 },
  { id: "level-3-5", level: 3, code: "LEVEL 3-5", zhName: "神枪手止剑", score: 3 },
  { id: "level-3-6", level: 3, code: "LEVEL 3-6", zhName: "大鸟，止剑", score: 3 },
  { id: "level-3-7", level: 3, code: "LEVEL 3-7", zhName: "小丑大皿，止剑", score: 3 },
  { id: "level-3-8", level: 3, code: "LEVEL 3-8", zhName: "欧洲一周", score: 3 },
  { id: "level-3-9", level: 3, code: "LEVEL 3-9", zhName: "中皿，升龙，止剑", score: 3 },
  { id: "level-3-10", level: 3, code: "LEVEL 3-10", zhName: "飞行机，中皿，天中杀", score: 3 },

  { id: "level-4-1", level: 4, code: "LEVEL 4-1", zhName: "飞行V，灯台，持球收", score: 4 },
  { id: "level-4-2", level: 4, code: "LEVEL 4-2", zhName: "螺旋飞行机", score: 4 },
  { id: "level-4-3", level: 4, code: "LEVEL 4-3", zhName: "安德鸟，持剑收", score: 4 },
  { id: "level-4-4", level: 4, code: "LEVEL 4-4", zhName: "美国一周", score: 4 },
  { id: "level-4-5", level: 4, code: "LEVEL 4-5", zhName: "鸟渡，止剑", score: 4 },
  { id: "level-4-6", level: 4, code: "LEVEL 4-6", zhName: "中皿极意，持球收", score: 4 },
  { id: "level-4-7", level: 4, code: "LEVEL 4-7", zhName: "1回转月面，月上1回，持球收", score: 4 },
  { id: "level-4-8", level: 4, code: "LEVEL 4-8", zhName: "小丑止剑", score: 4 },
  { id: "level-4-9", level: 4, code: "LEVEL 4-9", zhName: "竹马，天中杀收", score: 4 },
  { id: "level-4-10", level: 4, code: "LEVEL 4-10", zhName: "游泳，离转地球，反离转地球", score: 4 },

  { id: "level-5-1", level: 5, code: "LEVEL 5-1", zhName: "丹麦一周", score: 5 },
  { id: "level-5-2", level: 5, code: "LEVEL 5-2", zhName: "竹马，竹马渡，1转回持球收", score: 5 },
  { id: "level-5-3", level: 5, code: "LEVEL 5-3", zhName: "飞行机，1.5跳剑小丑止剑", score: 5 },
  { id: "level-5-4", level: 5, code: "LEVEL 5-4", zhName: "幽灵灯，小丑幽灵灯，持球收", score: 5 },
  { id: "level-5-5", level: 5, code: "LEVEL 5-5", zhName: "神枪手Late离转小丑止剑", score: 5 },
  { id: "level-5-6", level: 5, code: "LEVEL 5-6", zhName: "游泳，离转Late反离转止剑", score: 5 },
  { id: "level-5-7", level: 5, code: "LEVEL 5-7", zhName: "Tap小丑止剑", score: 5 },
  { id: "level-5-8", level: 5, code: "LEVEL 5-8", zhName: "飞机，2 Tap 1回转持球收", score: 5 },
  { id: "level-5-9", level: 5, code: "LEVEL 5-9", zhName: "飞行机，逆3圈跳剑", score: 5 },
  { id: "level-5-10", level: 5, code: "LEVEL 5-10", zhName: "飞行机，逆倒奶抛幽灵灯，持球收", score: 5 },

  { id: "level-6-1", level: 6, code: "LEVEL 6-1", zhName: "小丑一周", score: 6 },
  { id: "level-6-2", level: 6, code: "LEVEL 6-2", zhName: "竹马，小丑大鸟，幽灵持球收", score: 6 },
  { id: "level-6-3", level: 6, code: "LEVEL 6-3", zhName: "淘气鸟，重力持球收", score: 6 },
  { id: "level-6-4", level: 6, code: "LEVEL 6-4", zhName: "安德鸟，重力企鹅安德鸟往返，地球止剑", score: 6 },
  { id: "level-6-5", level: 6, code: "LEVEL 6-5", zhName: "飞行机，跳剑1-2-3", score: 6 },
  { id: "level-6-6", level: 6, code: "LEVEL 6-6", zhName: "逆月面，1回转Tap逆1回转逆月面，1回转Tap逆1回转持球收", score: 6 },
  { id: "level-6-7", level: 6, code: "LEVEL 6-7", zhName: "2 Tap小丑止剑", score: 6 },
  { id: "level-6-8", level: 6, code: "LEVEL 6-8", zhName: "1回转灯台Insta 1回转换神枪手小丑止剑", score: 6 },
  { id: "level-6-9", level: 6, code: "LEVEL 6-9", zhName: "极意一周", score: 6 },
  { id: "level-6-10", level: 6, code: "LEVEL 6-10", zhName: "离转小丑离转小丑止剑", score: 6 },

  { id: "level-7-1", level: 7, code: "LEVEL 7-1", zhName: "2圈Stankflip小丑止剑（剑击打球后旋转）", score: 7 },
  { id: "level-7-2", level: 7, code: "LEVEL 7-2", zhName: "淘气鸟，翻转淘气鸟渡，地球止剑", score: 7 },
  { id: "level-7-3", level: 7, code: "LEVEL 7-3", zhName: "1回转手臂灯台Insta小丑企鹅止剑", score: 7 },
  { id: "level-7-4", level: 7, code: "LEVEL 7-4", zhName: "银河一周", score: 7 },
  { id: "level-7-5", level: 7, code: "LEVEL 7-5", zhName: "游泳，神枪手地球123", score: 7 },
  { id: "level-7-6", level: 7, code: "LEVEL 7-6", zhName: "2大Tap换抛1.5圈持球收", score: 7 },
  { id: "level-7-7", level: 7, code: "LEVEL 7-7", zhName: "游泳，小丑止剑，2圈小丑止剑，3圈小丑止剑", score: 7 },
  { id: "level-7-8", level: 7, code: "LEVEL 7-8", zhName: "3 Tap战斧，持球收", score: 7 },
  { id: "level-7-9", level: 7, code: "LEVEL 7-9", zhName: "天中杀，1.5回转换玉中杀快手", score: 7 },
  { id: "level-7-10", level: 7, code: "LEVEL 7-10", zhName: "4 Tap小丑天中杀", score: 7 },

  { id: "level-8-1", level: 8, code: "LEVEL 8-1", zhName: "10小丑（或更多）止剑", score: 8 },
  { id: "level-8-2", level: 8, code: "LEVEL 8-2", zhName: "3神枪手大鸟，3神枪手止剑", score: 8 },
  { id: "level-8-3", level: 8, code: "LEVEL 8-3", zhName: "逆月面，逆月上1-2-3，持球收", score: 8 },
  { id: "level-8-4", level: 8, code: "LEVEL 8-4", zhName: "Tap小丑换手Tap换手小丑止剑", score: 8 },
  { id: "level-8-5", level: 8, code: "LEVEL 8-5", zhName: "2神枪手Late离转止剑，2神枪手Late离转地球", score: 8 },
  { id: "level-8-6", level: 8, code: "LEVEL 8-6", zhName: "飞行机，1.5跳剑Late 3离转1.5持球收", score: 8 },
  { id: "level-8-7", level: 8, code: "LEVEL 8-7", zhName: "Tap小丑x3止剑", score: 8 },
  { id: "level-8-8", level: 8, code: "LEVEL 8-8", zhName: "游泳大皿极意，小丑大皿极意，地球止剑", score: 8 },
  { id: "level-8-9", level: 8, code: "LEVEL 8-9", zhName: "逆月面，一回Cushion小丑Cushion逆月，持球收", score: 8 },
  { id: "level-8-10", level: 8, code: "LEVEL 8-10", zhName: "玉中杀，3圈玉中杀快手", score: 8 },

  { id: "level-9-1", level: 9, code: "LEVEL 9-1", zhName: "大皿极意一周，地球止剑", score: 9 },
  { id: "level-9-2", level: 9, code: "LEVEL 9-2", zhName: "1.5圆月提线大鸟，止剑", score: 9 },
  { id: "level-9-3", level: 9, code: "LEVEL 9-3", zhName: "飞行机，1.5跳剑小丑，反离转小丑x3，抛1.5圈持球入", score: 9 },
  { id: "level-9-4", level: 9, code: "LEVEL 9-4", zhName: "燕返一周，地球止剑", score: 9 },
  { id: "level-9-5", level: 9, code: "LEVEL 9-5", zhName: "天中杀转手手臂停剑，转身接剑", score: 9 },
  { id: "level-9-6", level: 9, code: "LEVEL 9-6", zhName: "1回转灯台Insta 1回转抛灯Insta2回转抛灯Insta 3回转持剑收", score: 9 },
  { id: "level-9-7", level: 9, code: "LEVEL 9-7", zhName: "神枪手逆抛剑Tap小丑Late神枪手逆抛剑Tap换手收剑", score: 9 },
  { id: "level-9-8", level: 9, code: "LEVEL 9-8", zhName: "逆月上3回x3，持球收", score: 9 },
  { id: "level-9-9", level: 9, code: "LEVEL 9-9", zhName: "6 Tap小丑止剑", score: 9 },
  { id: "level-9-10", level: 9, code: "LEVEL 9-10", zhName: "2大Tap换2Tap小丑鸟，天中杀", score: 9 },

  { id: "level-10-1", level: 10, code: "LEVEL 10-1", zhName: "离转Late离转Late离转小丑离转Late离转小丑离转止剑", score: 10 },
  { id: "level-10-2", level: 10, code: "LEVEL 10-2", zhName: "飞行机，3跳剑换烛台中皿极意，离转天中杀", score: 10 },
  { id: "level-10-3", level: 10, code: "LEVEL 10-3", zhName: "1回转灯台（Insta灯上1回x9）Insta 1回转持剑收", score: 10 },
  { id: "level-10-4", level: 10, code: "LEVEL 10-4", zhName: "烛台中皿极意，1.5小丑中皿极意，1.5小丑汤勺拿法中皿极意，天中杀快手", score: 10 },
  { id: "level-10-5", level: 10, code: "LEVEL 10-5", zhName: "大鸟，膝弹1回转大鸟，止剑", score: 10 },
  { id: "level-10-6", level: 10, code: "LEVEL 10-6", zhName: "大Tap-3Tap小丑离转小丑快手灯台，大Tap-Tap小丑离转小丑天中杀", score: 10 },
  { id: "level-10-7", level: 10, code: "LEVEL 10-7", zhName: "逆月面，1回转Tap逆1回转逆月面Insta 1回转Late神枪手抛剑Tap逆1回转逆月面Insta 1回转Tap逆1回转持球收", score: 10 },
  { id: "level-10-8", level: 10, code: "LEVEL 10-8", zhName: "3圈逆抛剑Tap小丑x2，3圈逆抛剑Tap持剑收", score: 10 },
  { id: "level-10-9", level: 10, code: "LEVEL 10-9", zhName: "4 Tap 1.5小丑汤勺拿法换烛台拿法1.5小丑4 Tap小丑幽灵抛剑玉中杀快手", score: 10 },
  { id: "level-10-10", level: 10, code: "LEVEL 10-10", zhName: "圆月1-2-3.5离转小丑Late圆月小丑天中杀", score: 10 },
];
